### ISSUE TITLE
Allow insecure incoming connections

### ISSUE THREAD

**Issue by ConradSchmidt** [naugtur/https-proxy-cli#7]
When using the https-proxy the server shuts down with something like this:
```
Error: self signed certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1042:34)
at TLSSocket.emit (events.js:159:13)
at TLSSocket._finishInit (_tls_wrap.js:639:8)
```

For development reasons this feature would be useful.

Solution
```
httpProxy.createServer({
  target: argv.target,
  ssl: {
    key: keys.serviceKey,
    cert: keys.certificate
  },
  secure: !argv.insecure
})
```

**Comment by naugtur** [comment]
It looks like you're proxyimg a server that already is https. I don't understand your use case.

**Comment by ConradSchmidt** [comment]
I used it to reroute traffic (locally) to a different port, but if you think this is not useful, it's fine.
Thanks for this nice tool :) very handy!

**Comment by naugtur** [comment]
You don't need an active proxy to reroute traffic to a different port, you can do that with a lower network layer tool. A ssh tunnel would suffice. Or local network configuration. 
https://serverfault.com/questions/251225/alias-port-port-forwarding-to-another-local-port

I don't mind adding `secure: false` as default, because it's supposed to handle http anyway.
Would you like to make it a pull request? :)

**Comment by ConradSchmidt** [comment]
I did it as an option, but you can reject it and I change it to the default.
